version: 2

models:
  - name: stg_adverse_events
    description: "Staging table for adverse events"
    tags: ["staging"]
    columns:
      - name: safetyreportid
        tests:
          - not_null
      - name: drug_id
        tests:
          - not_null
      - name: patient_id
        tests:
          - not_null
      - name: receivedate
        tests:
          - not_null

  - name: adverse_event_obt
    description: " 'One Big Table' for adverse events - serves as a base table for all analysis"
    tags: ["obt"]
    columns:
      - name: safety_report_id
        description: "identifier for the safety report"
        tests:
          - not_null
      - name: drug_name
        description: "Name of the drug"
      - name: drug_product
        description: "Medicinal product name"
      - name: drug_characterization
        description: "Characterization of the drug"
      - name: drug_indication
        description: "Indication of the drug"
      - name: patient_age
        description: "Age of the patient"
      - name: patient_age_unit
        description: "Unit of the patient's age"
      - name: age_group
        description: "Age group of the patient"
      - name: patient_weight_kg
        description: "Weight of the patient in kg"
      - name: patient_weight_lbs
        description: "Weight of the patient in lbs"
      - name: patient_sex
        description: "Sex of the patient"
      - name: reporter_country
        description: "Country of the reporter"
      - name: reaction_meddra_pt
        description: "MedDRA preferred term for the reaction"
      - name: reaction_outcome_cd
        description: "Outcome of the reaction"
      - name: mapped_outcome
        description: "Mapped outcome of the reaction"
      - name: receipt_date
        description: "Date the report was received"
      - name: receive_date
        description: "Date the report was received" 
      - name: receive_date_year
        description: "Year of the receive date"
      - name: receive_date_month
        description: "Month of the receive date"
      - name: receive_date_quarter
        description: "Quarter of the receive date"
      - name: is_serious
        description: "Indicates if the event is serious"
      - name: seriousness_death
        description: "Indicates if the event resulted in death"
      - name: seriousness_hospitalization
        description: "Indicates if the event resulted in hospitalization" 
      - name: seriousness_life_threatening
        description: "Indicates if the event resulted in life-threatening"
      - name: seriousness_disabling
        description: "Indicates if the event resulted in disabling"
      - name: seriousness_congenital_anomaly
        description: "Indicates if the event resulted in congenital anomaly"
      - name: seriousness_other
        description: "Indicates if the event resulted in other" 
      - name: date_pulled
        description: "Date the report was pulled AKA timestamp"
    tests:
      - unique_combination:
          combination: ['safety_report_id', 'drug_name']

  - name: dim_date
    description: "Dimension table for dates"
    tags: ["dims"]
    columns:
      - name: date_key
        description: "Day of the date"
        tests:
          - unique
          - not_null

  - name: age_group_analysis
    description: "Analysis of adverse events by age group"
    tags: ["analysis"]
    columns:
      - name: drug_name
        description: "Name of the drug"
      - name: age_group
        description: "Age group of the patients"
      - name: event_count
        description: "Count of adverse events"

  - name: reaction_analysis
    description: "Analysis of adverse events by reaction"
    tags: ["analysis"]
    columns:
      - name: drug_name
        description: "Name of the drug"
      - name: reaction_meddra_pt
        description: "MedDRA preferred term for the reaction"
      - name: date_year
        description: "Year of the event"
      - name: date_month
        description: "Month of the event"
      - name: reaction_count
        description: "Count of reactions"
      - name: percentage
        description: "Percentage of reactions for the drug"

  - name: time_based_analysis
    description: "Time-based analysis of adverse events"
    tags: ["analysis"]
    columns:
      - name: drug_name
        description: "Name of the drug"
      - name: date_year
        description: "Year of the event"
      - name: date_month
        description: "Month of the event"
      - name: monthly_event_count
        description: "Count of adverse events per month"

  - name: seriousness_analysis
    description: "Analysis of the seriousness of adverse events"
    tags: ["analysis"]
    columns:
      - name: drug_name
        description: "Name of the drug"
      - name: serious_count
        description: "Count of serious events"
      - name: death_count
        description: "Count of events resulting in death"
      - name: hospitalization_count
        description: "Count of events resulting in hospitalization"
      - name: life_threatening_count
        description: "Count of life-threatening events"
      - name: disabling_count
        description: "Count of disabling events"
      - name: congenital_anomaly_count
        description: "Count of events resulting in congenital anomalies"
      - name: other_serious_count
        description: "Count of other serious events"
      - name: total_events
        description: "Total count of events"
      - name: serious_percentage
        description: "Percentage of serious events"